import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen text-center">
        <div className="flex flex-wrap gap-3 p-4">
          <Card {...ExampleDrink} />
          <Card {...ExampleDrink2} />
          <Card {...ExampleDrink} />
          <Card {...ExampleDrink} />
          <Card {...ExampleDrink} />
        </div>
      </main>
    </>
  );
};

interface Drink {
  name: string;
  img: string;
  ingredients: { ingredient: string; parts: number }[];
  description: string;
  tags: string[];
}

const Card = ({ name, img, ingredients, description, tags }: Drink) => {
  return (
    <div className="w-[20rem] rounded-xl">
      <div className="z-10 overflow-clip rounded-xl">
        <img src={img} alt={`${name} preview`} />
      </div>
      <div className="relative z-20 mt-[-2rem] w-full rounded-xl bg-slate-600 p-2">
        <h2 className="text-lg">{name}</h2>
        <h3>Ingredients</h3>
        <ul>
          {ingredients.map((ingredient) => (
            <li>
              {ingredient.ingredient}: {ingredient.parts}
            </li>
          ))}
        </ul>
        <p>{description}</p>
        <h3>Tags</h3>
        <ul>
          {tags.map((tag) => (
            <li>
              <a href={`/${tag}`}>{tag}</a>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
};

const ExampleDrink: Drink = {
  name: "Whiskey Sour",
  img: "https://www.liquor.com/thmb/rSW8d-pqfyCGrTNAI4rmhfB9BWI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/whiskey-sour-720x720-primary-v2-4fc831b613964da5a19cdbfda917d7df.jpg",
  ingredients: [{ ingredient: "Whiskey", parts: 2 }],
  description: "Classic Whiskey Drink",
  tags: ["sour", "classic"],
};

const ExampleDrink2: Drink = {
  name: "Whiskey Sour",
  img: "https://www.liquor.com/thmb/rSW8d-pqfyCGrTNAI4rmhfB9BWI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/whiskey-sour-720x720-primary-v2-4fc831b613964da5a19cdbfda917d7df.jpg",
  ingredients: [
    { ingredient: "Whiskey", parts: 1.5 },
    { ingredient: "Simple Syrup", parts: 0.5 },
    { ingredient: "Lemon Juice", parts: 1 },
  ],
  description: "Classic Whiskey Drink",
  tags: ["sour", "classic"],
};

export default Home;
